# Fast running checks for pull-requests

name: Pull-Request Checks
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  pull_request

jobs:
  check-merge-commits:
    name: Check for Merge Commits
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/checkMergeCommits.yml@master
  check-compiles:
    name: Check if Code Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Check if code compiles
        run: mvn --batch-mode --update-snapshots compile