# Fast running checks for pull-requests

name: Pull-Request Checks
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  pull_request

jobs:
  check-merge-commits:
    name: Check for Merge Commits
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/checkMergeCommits.yml@master
  check-compiles:
    name: Check if Code Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Check if code compiles
        run: mvn --batch-mode --update-snapshots compile
  check-regressing-tests:
    name: Check for New Passes/Failures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Setup JBang
        uses: jbangdev/setup-jbang@312c53a4221283f9c8e4aa84d8261b82f0c680fb
      - name: Trust datho7561's Scripts
        run: jbang trust add https://gist.github.com/datho7561/
      - name: Run diffing script
        run: |
          set -o pipefail
          xvfb-run -a jbang https://gist.github.com/datho7561/a6be9caa9dbf2a69f097bd9a82dfa770 -v 2>&1 | tee results.txt
        continue-on-error: true
      - name: Fail if regressing
        run: "grep 'New failures:' results.txt && exit $(cat results.txt | grep 'New failures:' | sed -n 's/New failures: //p')"
